- .gitignore
- .npmrc
> chore: tell npm to work sans package-lock.json

- src/index.ts
This commit builds on #115, and contains just the reorganization part of #113.
> Sort rules

- src/index.test.ts
- src/index.ts
> fix: remove explicit-member-accessibility

- src/fixture.ts
- src/index.test.ts
- src/index.ts
This fixes #110, looser version.
> fix: loosen explicit-function-return-type

- package.json
BREAKING CHANGE: eslint-config-standard@^14.0.0
> chore: standard v14

- package.json
> fix: drop peerDependency of eslint-config-standard

- readme.md
> docs: add package versions to install command

- src/index.test.ts
- src/index.ts
> fix: add vars:all to no-unused-vars

- package.json
- src/index.test.ts
> fix: peer dependencies

- readme.md
> docs: vscode instructions

- package.json
- src/index.test.ts
> fix(deps): bump parser dep to match plugin

- package.json
> chore(package): update husky to version 4.0.6

- package.json
- src/index.test.ts
- src/index.ts
In rule no-empty-function allow protected and private constructors.
> feat: upgrade plugin & parser to v2.10.0

- src/index.test.ts
- src/index.ts
> fix: disable no-dupe-class-members

- src/index.test.ts
- src/index.ts
[ ] Bug fix
[x] New feature
Allow numbers in template literals.
#239 
n/a
> feat: allow numbers in template string interpolations

- src/index.test.ts
- src/index.ts
> fix: remove @typescript-eslint/no-empty-function

- package.json
[x] Bug fix
Bumped the version to get standard/eslint-config-standard#164 in
Fixes #258 
n/a
> Bump dependency on eslint-config-standard

- src/index.test.ts
- src/index.ts
[x] Bug fix
This removes `@typescript-eslint/require-await`
Fixes #217
I really appreciate all the time spent discussing this in detail!
> fix: remove @typescript-eslint/require-await

- readme.md
[x] Documentation update
[ ] Bug fix
fix indent on code example
documentation
JSON syntax
> fix indent on code example

- readme.md
[X] Documentation update
[ ] Bug fix
I just fix the broken link.
> docs: update the link to ESLint --ext option in readme

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule @typescript-eslint/method-signature-style
> feat: rule @typescript-eslint/method-signature-style

- src/index.test.ts
- src/index.ts
> feat: allowSingleExtends in no-empty-interface

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: peer dep version bump
Closes #209.
> chore(deps): bump parser & plugin to v3.0.1

- package.json
> fix: include lib/eslint-config-standard in package

- src/index.test.ts
- src/index.ts
[x] Bug fix
Allowed `PascalCase` for variables
#332 
n/a
-----
@mightyiam I would be very happy if we could release 18.0.2 with this fix as soon as possible, as this is currently blocking me from upgrading 😅 ❤️
> fix: allow PascalCase format on variables

- src/index.test.ts
> fix(test): deps parser & plugin same major version

- readme.md
[x] Documentation update
[ ] Bug fix
Bump the `@typescript-eslint/eslint-plugin` version number to 4 in the usage section of the readme, because since the 19.0.0 
release the minimum supported version of `@typescript-eslint/eslint-plugin` is 4.0.1.
> fix(docs): install version of @typescript-eslint/eslint-plugin@4

- src/index.test.ts
- src/index.ts
Fix #370
[x] Bug fix
Enable allowAsASStatement in no-void
Fixes #370
Run `yarn lint` in
https://codesandbox.io/s/quirky-hopper-sxtqw
to see the fixed behaviors.
> fix(no-void): enable allowAsStatement

- package.json
- readme.md
- src/index.test.ts
> fix: peer-depend on any version of typescript

- renovate.json
- src/index.test.ts
- test: rewrite some dep version tests
- chore: pull in renovate config
> some maintenance

- readme.md
[x] Documentation update
[ ] Bug fix
Update CI Badge
Fixes #834 
> docs: update ci badge

- readme.md
- docs: overhaul
- docs: add section on @typescript-eslint` dependencies
[ ] Bug fix
> typescript eslint readme update

- renovate.json
closes #850
closes #760
closes #668
> build(renovate): rewrite config

- src/index.test.ts
> refactor(tests): use semver to assert on ranges

- renovate.json
> build: renovate automergeMinor github actions

- package.json
- src/index.test.ts
> chore(deps): update dependency read-pkg-up to v9.1.0

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule consistent-indexed-object-style
> feat: add rule consistent-indexed-object-style

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: @typescript-eslint/ban-ts-comment
Co-authored-by: Shahar Dawn Or <mightyiampresence@gmail.com>
> feat: @typescript-eslint/ban-ts-comment

- package.json
- readme.md
- src/index.test.ts
- test: bottom peerDep compatibility test actually works
- fix: bump minimum @typescript-eslint to 5.50.0
> bump minimum @typescript-eslint to 5.50.0

- .github/workflows/ci.yaml
- get-node-supported-versions.sh
> fix: retrieval of active node versions in ci

- src/index.test.ts
> build: rm redundant peerDep range test

- package.json
> feat: bump eslint-config-standard to v17.1.0

- .github/workflows/ci.yaml
- .npmrc
- package-lock.json
> build: package-lock.json

- .github/workflows/ci.yaml
- commitlint.config.js
- package-lock.json
- package.json
- src/index.test.ts
> build: shared commitlint config

- package-lock.json
- package.json
- src/index.test.ts
- tsconfig.json
> build: moduleResolution: nodenext

- package-lock.json
- package.json
- readme.md
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: there will be some
> feat: @typescript-eslint 6

- src/inclusion.d.ts
> refactor: remove now unneeded types definition src/inclusion.d.ts

- .eslintrc.json
- readme.md
- src/index.test.ts
- src/index.ts
> feat: parserOptions.project=true

- tsconfig.json
> build: tsconfig.module = nodenext

- renovate.json
> build: automergeMinor eslint-config-standard

- package.json
- readme.md
- src/fixture.ts
> docs: update repository urls

- renovate.json
> build: merge-in renovate dependency

- .github/workflows/ci.yaml
> build(commitlint): don't use a github action

- src/index.test.ts
- src/index.ts
> test: config type change

- src/index.ts
- src/test/_util.ts
- src/test/resolved-config.ts
closes #1003
BREAKING CHANGE: (trying to) specify all options for rules that are used.
Most likely will not affect you.
> feat: try to specify all options for used rules

- src/test/resolved-config.ts
> chore: separate resolved config tests

- src/index.ts
- src/test/_util.ts
- src/test/resolved-config.ts
BREAKING CHANGE: no longer provides env nor globals.
> feat: do not specify env nor globals

- src/test/_util.ts
- src/test/compatibility.ts
- src/test/dependencies.ts
- **chore: rename a test util**
- **chore: rewrite dep range types test**
> rewrite some tests

- package-lock.json
- package.json
> chore: rm relic release scripts

- package-lock.json
- package.json
> chore(deps): @arkweid/lefthook -> lefthook

- package.json
> fix: include build artifacts in package

- src/test/equivalents.ts
- src/test/rules-to-consider.ts
> test: no import sub-dep @typescript-eslint/eslint-plugin

- package-lock.json
> chore(deps): npm update --all

- README.md
- **docs: move p about mobbing**
- **docs: description**
- **docs: "no framework/library-specific rules"**
> some readme changes

- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
> feat!: @typescript-eslint/no-confusing-non-null-assertion

- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
> feat!: @typescript-eslint/no-duplicate-type-constituents

- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
> feat!: @typescript-eslint/no-empty-function

- package.json
> chore: package.json funding field

- src/fixture.ts
- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
- src/test/_util.ts
- src/test/compatibility.ts
- src/test/resolved-config.ts
- src/test/rules.ts
> feat!: @typescript-eslint/no-magic-numbers

- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
> feat!: @typescript-eslint/no-meaningless-void-operator

- src/rules.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
> feat!: @typescript-eslint/no-unnecessary-qualifier

- src/_intentionally-unused-rules.ts
- src/rules.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
> feat!: no-new-native-nonconstructor

- src/rules.ts
- src/test/_expected-exported-value.ts
> feat: no-magic-numbers.enforceConst: false

- package-lock.json
- package.json
- src/test/compatibility.ts
> fix: bump incorrect typescript-eslint peerDep

- package-lock.json
- package.json
- src/test/compatibility.ts
- src/types.d.ts
> test: minimum eslint version

- eslint.config.cjs
- src/index.ts
- src/test/_expected-exported-value.ts
> feat!: linterOptions.reportUnusedDisableDirectives error

- src/_intentionally-unused-rules.ts
- src/rules.ts
- src/test/_expected-exported-value.ts
> feat: rm no-redeclare

- package-lock.json
- package.json
- renovate.json
- src/test/misc.ts
> fix: add missing @typescript-eslint/utils dep

- commitlint.config.js
- eslint.config.js
- package-lock.json
- package.json
- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_util.ts
- src/test/compatibility.ts
- src/test/dependencies.ts
- src/test/export.ts
- src/test/misc.ts
- src/test/resolved-config.ts
- src/test/rules.ts
- src/types.d.ts
- tsconfig.json
> feat!: package is in ecmascript module format

- src/rules.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
- **feat!: arrow-body-style**
- **feat!: arrow-body-style**
> arrow body style

- package-lock.json
- package.json
- src/rules/typescript-eslint.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
and bump minimum typescript-eslint@v8.12.0
> feat!: @typescript-eslint/switch-exhaustiveness-check

- package-lock.json
- package.json
- src/test/_util.ts
- src/test/integration.ts
> test: integration
