- src/index.ts
Because of https://github.com/nzakas/eslint-plugin-typescript/pull/84.
> no-unused-vars to warn

- .npmignore
- package-lock.json
- package.json
- readme.md
- src/fixture.ts
- src/index.ts
BREAKING CHANGE: peer depends on `eslint@^5.8.0`
Fixes #10
> chore: update all deps, update readme, add a fixture file

- .eslintrc.json
- package-lock.json
- package.json
- readme.md
- src/index.ts
BREAKING CHANGE: Users would have to:
- uninstall `typescript-eslint-parser eslint-plugin-typescript`
- install `@typescript-eslint/parser @typescript-eslint/eslint-plugin`
- determine whether their TypeScript version is compatible
- ESLint configuration:
- change `parser` to `@typescript-eslint/parser`
- add `parserOptions.project`
- tend to possible new linting errors from:
- several new added rules
- numerous fixed rules
> chore: update to the new `@typescript-eslint`

- package.json
eslint-plugin-node is at 9.1.0
We should upgrade this peerDependency to ^9.0.0 or at least >=8.0.0
> Update eslint-plugin-node peerDependency to 9

- src/index.ts
I think this addresses the issue in https://github.com/mightyiam/eslint-config-standard-with-typescript/issues/66, but I'll go into more detail.
To use JSX in a TypeScript file, the compiler makes you give the file a `.tsx` extension. Besides for maybe including JSX, `.tsx` files are completely normal TypeScript files.
As a result of https://github.com/mightyiam/eslint-config-standard-with-typescript/pull/44, the rules in this config only apply to `.ts` files. This causes `.tsx` files to not be linted properly, with erroneous ESLint errors being reported, and typescript-eslint errors not being reported. I tested the change in this PR with one of my projects, and in that project alone, applying this config to `.tsx` files resolved 14 false positives and revealed 91 false negatives (I can …
> Apply rules to .tsx files

- .eslintrc.json
- package.json
- readme.md
- src/index.ts
BREAKING CHANGE: `eslint-config-standard` has been updated to `13.0.1`.
BREAKING CHANGE: Updatd all peer dependencies. Fixes #80. Fixes #94.
Added option for rule `@typescript-eslint/explicit-function-return-type`: `allowHigherOrderFunctions: true`.
BREAKING CHANGE: `typescript-eslint/parser` is no longer a `peerDependency`, but a `dependency`. Users should remove it from their configuration, as well. Closes #65.
Updated `@typescript-eslint/eslint-plugin` to `1.10.2`.
> feat: update ESLint & TypeScript plugin

- src/index.ts
The Standard.js rules allow unused parameters in functions.
Typescript also has `noUnusedParameters`, so users can enable / disable that as they see fit. Whatever users choose, eslint-config-standard-with-typescript shouldn't conflict with Standard.js itself.
> fix: [no-unused-vars] Allow unused parameters

- readme.md
- Along with other pieces, eslint-config-standard-with-typescript itself should be installed as well to make things work.
- JSON file doesn't allow putting comma at the end of last property unlike JavaScript object.
> Update README : add missing dependency  and fix typo

- src/index.test.ts
- src/index.ts
eslint-config-standard-with-typescript replaces several ESLint rules with @typescript-eslint equivalents, but it missed `no-use-before-define`. To help with this in the future, this commit also organizes the rules by section.
This PR will conflict with #112, so whichever one gets merged first, I'll rebase the other one to match.
> fix: [no-use-before-define] Disable eslint version

- package.json
- src/fixture.ts
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: added rule `@typescript-eslint/prefer-readonly` https://github.com/typescript-eslint/typescript-eslint/commit/76b89a5
BREAKING CHANGE: added rule `@typescript-eslint/strict-boolean-expressions` https://github.com/typescript-eslint/typescript-eslint/commit/34e7d1e
BREAKING CHANGE: replaced rule `@typescript-eslint/no-triple-slash-reference` with `@typescript-eslint/no-reference-import` https://github.com/typescript-eslint/typescript-eslint/commit/af70a59
> feat: @typescript-eslint/eslint-plugin@^1.12.0

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: added rule `@typescript-eslint/no-misused-promises` https://github.com/typescript-eslint/typescript-eslint/commit/28a131d
BREAKING CHANGE: added rule `@typescript-eslint/require-await` https://github.com/typescript-eslint/typescript-eslint/commit/807bc2d
Closes #101.
> feat: @typescript-eslint/eslint-plugin@^1.13.0

- package.json
- src/index.test.ts
- src/index.ts
> feat: upgrade typescript-eslint packages to v2.1

- src/index.test.ts
- src/index.ts
> fix: adjust two rules to imitate Standard

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: brace-style now supports TypeScript syntax.
> feat: upgrade typescript-eslint packages v2.2

- src/index.ts
> chore: import values for equivalent rules from Standard

- src/index.ts
**What is the purpose of this pull request? (put an "X" next to the item)**
Added a custom function that accomplishes the same results as `Object.fromEntries`.
`Object.fromEntries` is only supported on the latest version of Nodejs (v12). This change allows this lib to be used on older versions of Nodejs. Typescript does not transpile `Object.fromEntries` because the ts devs consider it to be a runtime feature (https://github.com/microsoft/TypeScript/issues/32803).
maybe this should just be reverted back to strings for simplicity?
> fix: replace Object.fromEntries with a custom function

- package.json
BREAKING CHANGE: add @typescript-eslint/no-unnecessary-condition
Closes #154.
> feat: upgrade plugin to v2.3.3

- package.json
- src/fixture.ts
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule @typescript-eslint/restrict-template-expressions
https://github.com/typescript-eslint/typescript-eslint/blob/v2.8.0/packages/eslint-plugin/docs/rules/restrict-template-expressions.md
BREAKING CHANGE: add rule @typescript-eslint/space-before-function-paren
https://github.com/typescript-eslint/typescript-eslint/blob/v2.8.0/packages/eslint-plugin/docs/rules/space-before-function-paren.md
BREAKING CHANGE: add rule @typescript-eslint/no-dynamic-delete
https://github.com/typescript-eslint/typescript-eslint/blob/v2.8.0/packages/eslint-plugin/docs/rules/no-dynamic-delete.md
Closes #175.
> feat: upgrade plugin to v2.8.0

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule prefer-includes:
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-includes.md
Added new rule typescript `prefer-includes`
Closes #148 
> feat(rules): add rule prefer-includes (#148)

- src/index.test.ts
- src/index.ts
[ ] Bug fix
[x] New feature
Replaced eslint default func-call-spacing with @typescript-eslint/func-call-spacing
#232 
No
> feat: use @typescript-eslint func-call-spacing equivalent

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: parser & plugin v2.22.0 required.
BREAKING CHANGE: added rule @typescript-eslint/no-base-to-string.
> feat: upgrade parser & plugin to 2.22.0

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: new rule @typescript-eslint/return-await always
Closes #199.
> feat: new rule @typescript-eslint/return-await always

- package.json
BREAKING CHANGE: parser & plugin upgraded to v2.24.0 and new rules.
New rules:
- @typescript-eslint/no-unsafe-call
- @typescript-eslint/no-unsafe-member-access
- @typescript-eslint/no-unsafe-return
Closes #247.
Closes #250.
> feat: upgrade parser & plugin to v2.24.0

- package.json
BREAKING CHANGE: plugin peerDep bumped to 2.29.0
Closes #272.
Closes #273.
Closes #277.
> fix: upgrade parser & plugin to 2.29.0

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule @typescript-eslint/prefer-reduce-type-parameter
https://github.com/typescript-eslint/typescript-eslint/blob/v2.29.0/packages/eslint-plugin/docs/rules/prefer-reduce-type-parameter.md
> feat: rule @typescript-eslint/prefer-reduce-type-parameter

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add extending rule @typescript-eslint/keyword-spacing
https://github.com/typescript-eslint/typescript-eslint/blob/v2.29.0/packages/eslint-plugin/docs/rules/keyword-spacing.md
> feat: rule @typescript-eslint/keyword-spacing

- package.json
> fix: specify typescript as peerDep

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: peerDep bump
BREAKING CHANGE: new rule @typescript-eslint/dot-notation
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/dot-notation.md
BREAKING CHANGE: new rule @typescript-eslint/lines-between-class-members
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/lines-between-class-members.md
BREAKING CHANGE: new rule @typescript-eslint/no-invalid-void-type
https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-invalid-void-type.md
Closes #290.
Closes #291.
Closes #295.
Closes #297.
> feat: upgrade parser & plugin to 2.33.0

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule @typescript-eslint/prefer-ts-expect-error
https://github.com/typescript-eslint/typescript-eslint/blob/v2.29.0/packages/eslint-plugin/docs/rules/prefer-ts-expect-error.md
> feat: rule @typescript-eslint/prefer-ts-expect-error

- readme.md
> fix(docs): install version of @typescript-eslint/eslint-plugin@3

- commitlint.config.js
- package.json
`commitlint-config-awesome` is less used/updated (not updated since Dec 16, 2019), break on `npm@7` because peerDependency don't match and we don't need it anymore because we don't use anymore `Greenkeeper`, also `@commitlint/config-conventional` is what it is used for `ts-standard`.
> chore: usage of @commitlint/config-conventional

- package.json
- src/index.test.ts
Fixes #596.
BREAKING CHANGE: peer dependencies are specified with `^`.
> fix(package): peerDeps use caret ranges

- src/index.test.ts
- src/index.ts
[X] Bug fix
Replaced `space-infix-ops` with `@typescript-eslint/space-infix-ops` as proposed in https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/space-infix-ops.md
This fixes the spacing around `|` in type definitions, like `arg: string | number` (instead of `string|number`).
I'm not sure that this would work here, because I'm using these configs with eslint@8
> fix: use typescript-eslint version of space-infix-ops rule

- package.json
- src/index.test.ts
BREAKING CHANGE: the dependency eslint-config-standard is now pinned.
closes #849
> feat: pin eslint-config-standard dependency

- package.json
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rules from @typescript-eslint: no-extra-parens,
no-loss-of-precision, object-curly-spacing, space-before-blocks,
comma-dangle.
Closes #582, closes #583.
> feat: use all typescript-eslint equivalents

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add @typescript-eslint/no-unnecessary-type-constraint
> feat: add @typescript-eslint/no-unnecessary-type-constraint

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add @typescript-eslint/await-thenable
Co-authored-by: Shahar Dawn Or <mightyiampresence@gmail.com>
> feat: add @typescript-eslint/await-thenable

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: @typescript-eslint/ban-tslint-comment
> feat: @typescript-eslint/ban-tslint-comment

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: @typescript-eslint/ban-types
> feat: @typescript-eslint/ban-types

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: @typescript-eslint/consistent-generic-constructors
> feat: @typescript-eslint/consistent-generic-constructors

- src/eslint-config-standard.ts
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: @typescript-eslint/consistent-type-{imports/exports}
> feat: @typescript-eslint/consistent-type-{imports/exports}

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: @typescript-eslint/class-literal-property-style
Co-authored-by: Shahar Dawn Or <mightyiampresence@gmail.com>
> feat: @typescript-eslint/class-literal-property-style

- src/index.test.ts
> test: equivalents not used upstream not considered

- package.json
- readme.md
- src/index.test.ts
And add test for this to never happen again
Fixes #1064
> fix: bump plugin peerDep

- renovate.json
Fixes #1083. At least, in theory.
> build(renovate): do not bump @typescript-eslint_bottom/*

- .eslintrc.json
- package.json
- readme.md
- src/index.test.ts
- src/index.ts
- tsconfig.json
BREAKING CHANGE: the rules are provided at the top level,
instead of under an `overrides` property.
Providing the rules under the `overrides` property was never a good idea.
It prevents specifying which files the rules apply to (e.g. `[*.js, *.ts]`).
I apologize.
To migrate, make sure that your `extends` property is under an [`overrides` item][overrides].
An example is in the readme.
To help verify your configuration,
you could obtain a list of files that will be linted, this way:
`DEBUG=eslint:cli-engine npx eslint <path>`.
[overrides]: https://eslint.org/docs/latest/use/configure/configuration-files#how-do-overrides-work
closes #1149
closes #1088
> fix: rules are at top level (not under overrides)

- package.json
- readme.md
- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule @typescript-eslint/block-spacing and bump
minimum @typescript-eslint to 5.52.0
> feat: @typescript-eslint/block-spacing

- package-lock.json
- package.json
- readme.md
BREAKING CHANGE: Technically, bumping a peer dependency version is a breaking change.
[X] Documentation update
[X] Bug fix
Updating `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to `v6.4.0`
Fix: https://github.com/standard/eslint-config-standard-with-typescript/issues/1202
> chore(deps): @typescript-eslint plugin and parser v6.4.0

- readme.md
- src/index.test.ts
[x] Documentation update
[ ] Bug fix
Update the install command in the readme for peer dependencies to quote strings with characters interpreted by shells like bash and zsh.
The install command as currently given is not usable in zsh without escaping the `^`s.
> feat(docs): replace npm@<7 with yarn

- src/index.test.ts
- src/index.ts
BREAKING CHANGE: add rule @typescript-eslint/unbound-method
Related to #1327
> feat: @typescript-eslint/unbound-method

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- **Revert "chore(deps): update @typescript-eslint packages to v6.21.0"**
- **Revert "chore(deps): update dependency typescript to v5.4.3"**
- **Revert "chore(deps): update dependency typescript to v5.4.2"**
- **build(ci): "ci" job explicitly fails if test matrix fails**
> revert and prevent unwanted auto bumps

- package-lock.json
- package.json
because deprecated prefer-ts-expect-error was removed
> fix(deps)!: typescript-eslint minimum v7.11.0

- README.md
From the note at https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/README.md:
> See https://typescript-eslint.io/packages/parser for documentation on this package.
> docs: README: Update parser config links

- src/_intentionally-unused-rules.ts
- src/index.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
remove redundant `@typescript-eslint/no-empty-interface`
> feat!: @typescript-eslint/no-empty-object-type

- src/index.ts
- src/test/_expected-exported-value.ts
Covered by @typescript-eslint/no-empty-object-type
> fix: rm empty object from @typescript-eslint/ban-types

- src/test/_util.ts
- src/test/compatibility.ts
- src/test/dependencies.ts
- src/test/misc.ts
> chore: use top level await for something

- src/rules.ts
- src/test/_expected-exported-value.ts
- src/test/_intentionally-unused-rules.ts
> fix: rm no-undef-init

- src/rules.ts
> fix: no use lodash in impl

- package-lock.json
- package.json
- src/plugin-usage/typescript-eslint.ts
- src/test/_expected-exported-value.ts
- src/test/_rules_to_consider.ts
- src/test/rules.ts
BREAKING CHANGE: @typescript-eslint/no-unsafe-type-assertion and
bump minimum typescript-eslint to v8.15.0.
> feat: @typescript-eslint/no-unsafe-type-assertion
